[package]
name = "yewcounter"
version = "0.1.0"
authors = ["Michael Milewski <saramic@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.2"
yew = "0.4.0"
